//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessionalniiTechnicheskiiYniversitet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProfTechnYniversitetEntities : DbContext
    {
        public ProfTechnYniversitetEntities()
            : base("name=ProfTechnYniversitetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Gruppa> Gruppa { get; set; }
        public virtual DbSet<Polzovatel> Polzovatel { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<Prepod> Prepod { get; set; }
        public virtual DbSet<SotrudnikDirekcii> SotrudnikDirekcii { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Attestaciya> Attestaciya { get; set; }
        public virtual DbSet<AttestaciyaStud> AttestaciyaStud { get; set; }
    }
}
