//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessionalniiTechnicheskiiYniversitet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prepod()
        {
            this.Predmet = new HashSet<Predmet>();
        }
    
        public int ID_Prepod { get; set; }
        public string FIOPrepod { get; set; }
        public int Login { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predmet> Predmet { get; set; }
    }
}
