//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessionalniiTechnicheskiiYniversitet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AttestaciyaStud = new HashSet<AttestaciyaStud>();
        }
    
        public int ID_Student { get; set; }
        public string FIOSTud { get; set; }
        public int ID_Guppa { get; set; }
        public int Login { get; set; }
    
        public virtual Gruppa Gruppa { get; set; }
        public virtual Polzovatel Polzovatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttestaciyaStud> AttestaciyaStud { get; set; }
    }
}
